/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ViewmemoriesRouteImport } from './routes/viewmemories'
import { Route as MemoriesRouteImport } from './routes/memories'
import { Route as GuestbookRouteImport } from './routes/guestbook'
import { Route as AddmemoriesRouteImport } from './routes/addmemories'
import { Route as IndexRouteImport } from './routes/index'

const ViewmemoriesRoute = ViewmemoriesRouteImport.update({
  id: '/viewmemories',
  path: '/viewmemories',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesRoute = MemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestbookRoute = GuestbookRouteImport.update({
  id: '/guestbook',
  path: '/guestbook',
  getParentRoute: () => rootRouteImport,
} as any)
const AddmemoriesRoute = AddmemoriesRouteImport.update({
  id: '/addmemories',
  path: '/addmemories',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/addmemories': typeof AddmemoriesRoute
  '/guestbook': typeof GuestbookRoute
  '/memories': typeof MemoriesRoute
  '/viewmemories': typeof ViewmemoriesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/addmemories': typeof AddmemoriesRoute
  '/guestbook': typeof GuestbookRoute
  '/memories': typeof MemoriesRoute
  '/viewmemories': typeof ViewmemoriesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/addmemories': typeof AddmemoriesRoute
  '/guestbook': typeof GuestbookRoute
  '/memories': typeof MemoriesRoute
  '/viewmemories': typeof ViewmemoriesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/addmemories' | '/guestbook' | '/memories' | '/viewmemories'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/addmemories' | '/guestbook' | '/memories' | '/viewmemories'
  id:
    | '__root__'
    | '/'
    | '/addmemories'
    | '/guestbook'
    | '/memories'
    | '/viewmemories'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddmemoriesRoute: typeof AddmemoriesRoute
  GuestbookRoute: typeof GuestbookRoute
  MemoriesRoute: typeof MemoriesRoute
  ViewmemoriesRoute: typeof ViewmemoriesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/viewmemories': {
      id: '/viewmemories'
      path: '/viewmemories'
      fullPath: '/viewmemories'
      preLoaderRoute: typeof ViewmemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories': {
      id: '/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof MemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guestbook': {
      id: '/guestbook'
      path: '/guestbook'
      fullPath: '/guestbook'
      preLoaderRoute: typeof GuestbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addmemories': {
      id: '/addmemories'
      path: '/addmemories'
      fullPath: '/addmemories'
      preLoaderRoute: typeof AddmemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddmemoriesRoute: AddmemoriesRoute,
  GuestbookRoute: GuestbookRoute,
  MemoriesRoute: MemoriesRoute,
  ViewmemoriesRoute: ViewmemoriesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
